Algoritmo "vetores"
// variável que armazena vários valores de um mesmo tipo de dado
//variável que armazena outra variável
Var
nomes: vetor[1..4] de caractere
indice: inteiro

Inicio
para indice de 1 ate 4 faca
escreval ("Digite um nome para a posição ", indice, " do vetor:")
leia (nomes[indice])
fimpara
 escreval ("-----------------------------------------")
 
para indice de 1 ate 4 faca
escreval (nomes[indice])
fimpara

Fimalgoritmo